import {
  Activity,
  Antenna,
  ArrowLeftRight,
  // ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AreaChart,
  Atom,
  BarChart3,
  Battery,
  Beaker,
  // Benzene,
  Binary,
  Box,
  Brain,
  Calculator,
  // ChainLink,
  Circle,
  // Coil,
  Cpu,
  // Crystal,
  Database,
  Diamond,
  Dice6,
  Dna,
  Droplet,
  Droplets,
  Ellipsis,
  Eye,
  Flame,
  FlaskConical,
  FlaskRound,
  Fuel,
  FunctionSquare,
  GitBranch,
  GitBranchPlus,
  GitCommit,
  Globe,
  Grid,
  Grid3X3,
  Hexagon,
  Home,
  Infinity,
  // Integral,
  Layers,
  Leaf,
  // Lens,
  LineChart,
  Link,
  List,
  Magnet,
  Microscope,
  Minus,
  // Molecule,
  Mountain,
  Move3D,
  Network,
  Octagon,
  Pentagon,
  Pickaxe,
  Pipette,
  // Polygon,
  Power,
  Radiation,
  Radio,
  Repeat,
  Repeat2,
  RotateCcw,
  RotateCw,
  Satellite,
  Scale,
  Scissors,
  Shapes,
  Shuffle,
  Smile,
  Square,
  // SquareRoot,
  Superscript,
  Target,
  TestTube,
  Thermometer,
  Timer,
  TreePine,
  TrendingUp,
  Triangle,
  // Venn,
  // Waveform,
  Waves,
  Wind,
  Wrench,
  Zap
} from "lucide-react";

export const chapterIconMap = {
  // Physics
  "Motion In Two Dimensions": <Repeat2 className="w-6 h-6 text-orange-500" />,
  "Laws of Motion": <Activity className="w-6 h-6 text-blue-500" />,
  "Work Power Energy": <Battery className="w-6 h-6 text-green-500" />,
  "Center of Mass Momentum and Collision": <Target className="w-6 h-6 text-red-500" />,
  "Rotational Motion": <RotateCcw className="w-6 h-6 text-purple-500" />,
  "Gravitation": <Globe className="w-6 h-6 text-indigo-500" />,
  "Mechanical Properties of Solids": <Box className="w-6 h-6 text-amber-500" />,
  "Mechanical Properties of Fluids": <Droplets className="w-6 h-6 text-cyan-500" />,
  "Thermal Properties of Matter": <Thermometer className="w-6 h-6 text-red-600" />,
  "Thermodynamics": <Flame className="w-6 h-6 text-orange-600" />,
  "Kinetic Theory of Gases": <Wind className="w-6 h-6 text-gray-500" />,
  "Oscillations": <Radio className="w-6 h-6 text-pink-500" />,
  "Waves and Sound": <Waves className="w-6 h-6 text-teal-500" />,
  "Electrostatics": <Zap className="w-6 h-6 text-yellow-500" />,
  "Capacitance": <Database className="w-6 h-6 text-blue-600" />,
  "Current Electricity": <Power className="w-6 h-6 text-green-600" />,
  "Magnetic Properties of Matter": <Magnet className="w-6 h-6 text-red-700" />,
  "Magnetic Effects of Current": <GitBranch className="w-6 h-6 text-purple-600" />,
  // "Electromagnetic Induction": <Coil className="w-6 h-6 text-indigo-600" />,
  // "Alternating Current": <Waveform className="w-6 h-6 text-emerald-500" />,
  "Electromagnetic Waves": <Satellite className="w-6 h-6 text-violet-500" />,
  "Ray Optics": <Eye className="w-6 h-6 text-pink-600" />,
  // "Wave Optics": <Lens className="w-6 h-6 text-cyan-600" />,
  "Dual Nature of Matter": <Binary className="w-6 h-6 text-slate-500" />,
  "Atomic Physics": <Atom className="w-6 h-6 text-blue-700" />,
  "Nuclear Physics": <Radiation className="w-6 h-6 text-yellow-600" />,
  "Semiconductors": <Cpu className="w-6 h-6 text-green-700" />,
  "Communication System": <Antenna className="w-6 h-6 text-orange-700" />,
  "Experimental Physics": <Microscope className="w-6 h-6 text-purple-700" />,

  // Chemistry
  "Some Basic Concepts of Chemistry": <FlaskConical className="w-6 h-6 text-blue-500" />,
  "Structure of Atom": <Atom className="w-6 h-6 text-green-500" />,
  "Classification of Elements and Periodicity in Properties": <Grid3X3 className="w-6 h-6 text-purple-500" />,
  "Chemical Bonding and Molecular Structure": <Link className="w-6 h-6 text-red-500" />,
  "States of Matter": <Hexagon className="w-6 h-6 text-orange-500" />,
  "Thermodynamics (C)": <Flame className="w-6 h-6 text-red-600" />,
  "Chemical Equilibrium": <Scale className="w-6 h-6 text-yellow-500" />,
  "Ionic Equilibrium": <Zap className="w-6 h-6 text-blue-600" />,
  "Redox Reactions": <ArrowLeftRight className="w-6 h-6 text-green-600" />,
  "Hydrogen": <Droplet className="w-6 h-6 text-cyan-500" />,
  "s Block Elements": <Square className="w-6 h-6 text-indigo-500" />,
  "p Block Elements (Group 13 & 14)": <Pentagon className="w-6 h-6 text-pink-500" />,
  // "General Organic Chemistry": <Benzene className="w-6 h-6 text-amber-500" />,
  "Hydrocarbons": <Fuel className="w-6 h-6 text-orange-600" />,
  "Environmental Chemistry": <Leaf className="w-6 h-6 text-green-700" />,
  // "Solid State": <Crystal className="w-6 h-6 text-purple-600" />,
  "Solutions": <Beaker className="w-6 h-6 text-teal-500" />,
  "Electrochemistry": <Battery className="w-6 h-6 text-yellow-600" />,
  "Chemical Kinetics": <Timer className="w-6 h-6 text-red-700" />,
  "Surface Chemistry": <Layers className="w-6 h-6 text-blue-700" />,
  "General Principles and Processes of Isolation of Metals": <Pickaxe className="w-6 h-6 text-amber-600" />,
  "p Block Elements (Group 15, 16, 17 & 18)": <Octagon className="w-6 h-6 text-violet-500" />,
  "d and f Block Elements": <Diamond className="w-6 h-6 text-emerald-600" />,
  "Coordination Compounds": <Network className="w-6 h-6 text-cyan-700" />,
  "Haloalkanes and Haloarenes": <Shapes className="w-6 h-6 text-pink-600" />,
  "Alcohols Phenols and Ethers": <TestTube className="w-6 h-6 text-green-800" />,
  "Aldehydes and Ketones": <FlaskRound className="w-6 h-6 text-orange-800" />,
  "Carboxylic Acid Derivatives": <Pipette className="w-6 h-6 text-red-800" />,
  // "Amines": <Molecule className="w-6 h-6 text-blue-800" />,
  "Biomolecules": <Dna className="w-6 h-6 text-purple-800" />,
  // "Polymers": <ChainLink className="w-6 h-6 text-yellow-700" />,
  "Chemistry in Everyday Life": <Home className="w-6 h-6 text-indigo-700" />,
  "Practical Chemistry": <Wrench className="w-6 h-6 text-slate-600" />,

  // Mathematics
  "Basic of Mathematics": <Calculator className="w-6 h-6 text-blue-500" />,
  "Quadratic Equation": <Superscript className="w-6 h-6 text-green-500" />,
  "Complex Number": <Binary className="w-6 h-6 text-purple-500" />,
  "Permutation Combination": <Shuffle className="w-6 h-6 text-red-500" />,
  "Sequences and Series": <List className="w-6 h-6 text-orange-500" />,
  "Mathematical Induction": <Repeat className="w-6 h-6 text-yellow-500" />,
  "Binomial Theorem": <TreePine className="w-6 h-6 text-green-600" />,
  "Trigonometric Ratios & Identities": <Triangle className="w-6 h-6 text-blue-600" />,
  "Trigonometric Equations": <FunctionSquare className="w-6 h-6 text-purple-600" />,
  "Straight Lines": <Minus className="w-6 h-6 text-red-600" />,
  "Pair of Lines": <Scissors className="w-6 h-6 text-orange-600" />,
  "Circle": <Circle className="w-6 h-6 text-cyan-500" />,
  "Parabola": <Smile className="w-6 h-6 text-pink-500" />,
  "Ellipse": <Ellipsis className="w-6 h-6 text-indigo-500" />,
  "Hyperbola": <Infinity className="w-6 h-6 text-teal-500" />,
  "Limits": <ArrowUpDown className="w-6 h-6 text-amber-500" />,
  "Mathematical Reasoning": <Brain className="w-6 h-6 text-violet-500" />,
  "Statistics": <BarChart3 className="w-6 h-6 text-emerald-500" />,
  "Heights and Distances": <Mountain className="w-6 h-6 text-blue-700" />,
  // "Properties of Triangles": <Polygon className="w-6 h-6 text-green-700" />,
  // "Sets and Relations": <Venn className="w-6 h-6 text-purple-700" />,
  "Matrices": <Grid className="w-6 h-6 text-red-700" />,
  "Determinants": <Square className="w-6 h-6 text-orange-700" />,
  "Inverse Trigonometric Functions": <RotateCw className="w-6 h-6 text-yellow-700" />,
  "Functions": <TrendingUp className="w-6 h-6 text-cyan-600" />,
  "Continuity and Differentiability": <GitCommit className="w-6 h-6 text-pink-600" />,
  "Differentiation": <ArrowUp className="w-6 h-6 text-indigo-600" />,
  "Application of Derivatives": <Wrench className="w-6 h-6 text-teal-600" />,
  // "Indefinite Integration": <Integral className="w-6 h-6 text-amber-600" />,
  // "Definite Integration": <SquareRoot className="w-6 h-6 text-violet-600" />,
  "Area Under Curves": <AreaChart className="w-6 h-6 text-emerald-600" />,
  "Differential Equations": <GitBranchPlus className="w-6 h-6 text-blue-800" />,
  "Vector Algebra": <Move3D className="w-6 h-6 text-green-800" />,
  "Three Dimensional Geometry": <Box className="w-6 h-6 text-purple-800" />,
  "Linear Programming": <LineChart className="w-6 h-6 text-red-800" />,
  "Probability": <Dice6 className="w-6 h-6 text-orange-800" />
};